name: Fullstack CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH to VPS
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 119.59.102.217 >> ~/.ssh/known_hosts

    - name: Deploy to VPS
      run: |
        ssh root@119.59.102.217 << 'EOF'
          echo "Deploy Started"

          # FRONTEND
          cd /var/www/frontend/OverseaSupplierWeb || exit 1
          git pull origin main
          npm install
          ng build --configuration production
          cp -r dist/* /var/www/html
        EOF
